name: Linux Build

on: push

jobs: 
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install wxWidgets
        run: |
          sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.5/ubuntu/ focal universe'
          sudo apt update
